//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFSAcademy
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINANCE_TRANSACTION_CATEGORY
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string DESCR { get; set; }
        public string IS_INCM { get; set; }
        public string DEL { get; set; }
    }
}
